-- Consolidated initial schema for powadb.db.
--
-- This is the cumulative shape the inline CREATE TABLE / ALTER TABLE
-- block in `storage.rs::Storage::open` produced before the migration
-- runner was introduced. Pre-existing installs that already have these
-- tables are stamped with `schema_version = 1` without rerunning this
-- file (see `storage_migrations::run`).
--
-- New schema changes should land as `0002_*.sql`, `0003_*.sql`, … —
-- do not edit this file.

CREATE TABLE IF NOT EXISTS connections (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    kind         TEXT NOT NULL,
    host         TEXT NOT NULL,
    port         INTEGER NOT NULL,
    database     TEXT NOT NULL,
    username     TEXT NOT NULL,
    ssl          INTEGER NOT NULL DEFAULT 0,
    password     TEXT,
    folder_id    TEXT,
    color        TEXT,
    wg_enabled   INTEGER NOT NULL DEFAULT 0,
    wg_config    TEXT,
    ssh_enabled  INTEGER NOT NULL DEFAULT 0,
    ssh_config   TEXT,
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS folders (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    parent_id  TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS query_history (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    connection_id TEXT NOT NULL,
    sql           TEXT NOT NULL,
    executed_at   TEXT NOT NULL DEFAULT (datetime('now')),
    elapsed_ms    INTEGER,
    row_count     INTEGER,
    error         TEXT
);

CREATE INDEX IF NOT EXISTS idx_history_conn_time
    ON query_history(connection_id, executed_at DESC);

CREATE TABLE IF NOT EXISTS snippets (
    id               TEXT PRIMARY KEY,
    connection_id    TEXT,
    name             TEXT NOT NULL,
    sql              TEXT NOT NULL,
    bytea_modes_json TEXT,
    created_at       TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS diagrams (
    id            TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    name          TEXT NOT NULL,
    doc_json      TEXT NOT NULL,
    created_at    TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_diagrams_connection
    ON diagrams(connection_id);

CREATE TABLE IF NOT EXISTS themes (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    base        TEXT NOT NULL,
    radius      TEXT NOT NULL,
    colors_json TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
